trigger:
  branches:
    include:
      - main  # Replace with your branch name

pool:
  name: 'deepak'  # Replace with your agent pool name

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      # Replace with your Python build commands
      pip install -r requirements.txt
      python3 'app.py'
    displayName: 'Build application'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'  # Replace with your build output directory
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive build output'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'deepakkk'
    appType: 'webApp'
    WebAppName: 'app'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    enableCustomDeployment: true
  displayName: 'Deploy to Azure App Service'
